### ISSUE TITLE
프로그래머스 리뷰 삭제

### ISSUE THREAD

**Issue by Yaminyam** [junghyeonsu/awesome-dev-activity-review#1]
- 글 제목: [취업준비] 프로그래머스 - 2021 Dev-Matching : 웹 백엔드 개발자 후기
- 작성자: Mark31
- 날짜: 
- 리뷰 링크:
- 기업: 프로그래머스
- 활동 종류: 링크의 게시글이 삭제됨

**Comment by junghyeonsu** [comment]
@Yaminyam 감사합니다 👍
