### ISSUE TITLE
네이버 웹툰 공채 합격 회고

### ISSUE THREAD

**Issue by backtony** [junghyeonsu/awesome-dev-activity-review#2]
- 글 제목: 2022 상반기 네이버웹툰 신입 공채 합격 회고
- 작성자: backtony
- 날짜: 2022/05/27
- 리뷰 링크: https://backtony.github.io/review/2022-05-27-review-1/
- 기업: 네이버 웹툰
- 활동 종류: 최종 합격 회고

**Comment by junghyeonsu** [comment]
@backtony 감사합니다. 추가되었습니다!
