### ISSUE TITLE
블로그 이전으로 인한 링크 수정 요청

### ISSUE THREAD

**Issue by backtony** [junghyeonsu/awesome-dev-activity-review#3]
종류 | 제목 | 작성자 | 날짜 |
| --- | --- | --- | --- |
| 네이버 웹툰 합격 후기 | [2022 상반기 백엔드 개발 취업 회고](https://velog.io/@backtony/2022-%EC%83%81%EB%B0%98%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-%EA%B0%9C%EB%B0%9C-%EC%B7%A8%EC%97%85-%ED%9A%8C%EA%B3%A0) | backtony | 2022/06/19 |

2022 상반기 네이버 웹툰 신입 공채 후기에 제 블로그 글이 있는데, 블로그를 이전해서 링크 수정 부탁드립니다.

**Comment by junghyeonsu** [comment]
적용되었습니다 감사합니다 :)
